---
- title: "練習自我對話"
  guidance_content: "試著用「我不需要/不用...」開頭，練習和自己對話（Self-talk），告訴自己："
  body_content: "<ul class='font content-hieght' style='margin: 0px;'>
                    <li>我不用在 IG 上確認所有朋友的近況。</li>
                    <li>我不用即時確認每個通知。</li>
                    <li>我不需要知道和我朋友有關的所有事情。</li>
                    <li>我不用在 IG 上花費大把時間，因為我有更重要的事情要去做。</li>
                </ul>"
- title: "保持正確的心態"
  guidance_content: "用正確的心態使用 IG，試著告訴自己即便「不這麼做」或是「事情與我預期的不同」，我也不會因此成為不好的人。你/妳可以說："
  body_content: "<ul class='font content-hieght' style='margin: 0px;'>
                    <li>不是只有我沒有在 IG 上如預期地與朋友互動。</li>
                    <li>我不會因為沒有即時回覆訊息而變得不受歡迎。</li>
                </ul>"
- title: "遠離 3C、減少焦慮"
  guidance_content: "試著放下手機、遠離 3C 產品，透過從事不需要上網的活動，可以分散你/妳的注意力並減少焦慮。你/妳可以試著："
  body_content: "<ul class='font content-hieght' style='margin: 0px;'>
                    <li>和朋友聚餐、聊天</li>
                    <li>打掃房間</li>
                    <li>到室外走走</li>
                    <li>做一些你/妳喜歡的事情（如：看書、聽音樂等）</li>
                </ul>"
- title: "問問自己"
  guidance_content: "試著以第三人稱的視角看待問題。想想看："
  body_content: "<ul class='font content-hieght' style='margin: 0px;'>
                    <li>想想你/妳現在正面臨的困擾或負面情緒...為什麼你/妳會有這樣的情緒呢？當你/妳的朋友面臨一樣的困擾的時候，你/妳會和他/她說什麼呢？</li>
                </ul>
                <br>
                <p class='font content-hieght'>你/妳也可以試著這樣告訴自己！</p>"
- title: "管理社群互動期待"
  guidance_content: "在使用 IG 之前，先想想下面幾件事情，避免對社群的互動有過高的期待："
  body_content: "<ul class='font content-hieght' style='margin: 0px;'>
                    <li>我本來就可能會錯過一些在 IG 上的訊息或貼文。</li>
                    <li>我可能不會收到朋友即時的回覆。</li>
                    <li>可能沒有（或很少）人回覆我的貼文或限時動態。</li>
                    <li>我的貼文或限時動態可能會因為演算法而不被顯示。</li>
                    <li>朋友可能因為在忙別的事情而沒辦法看到我的動態。</li>
                </ul>"
- title: "減少對 IG 的依賴"
  guidance_content: "試著用下面幾個方式減少對 IG 的依賴："
  body_content: "<ul class='font content-hieght' style='margin: 0px;'>
                    <li>不對 IG 的每則通知做出反應</li>
                    <li>練習從隨時查看 IG 改成每隔一段時間再看</li>
                    <li>做一些你/妳喜歡的事情轉移注意力</li>
                    <li>設定 IG 使用時間上限提醒：
                      <ol class='font content-hieght'>
                        <li>點選右下角的個人檔案</li>
                        <li>點選右上方「☰」</li>
                        <li>點選「你的動態」</li>
                        <li>點選「花費時間」</li>
                        <li>點選「設定休息一下的提醒」或「設定每日時間上限」進行設定</li>
                      </ol>
                    </li>
                </ul>"
- title: "篩選貼文與動態"
  guidance_content: "當你/妳使用 IG 感到情緒低落時，可以透過下面幾種方式篩選貼文與動態："
  body_content: "<p class='font content-hieght'>如果是因為看到某個特定朋友的動態而感到情緒低落，你/妳可以試著：</p>
                <ul class='font content-hieght' style='margin: 0px;'>
                    <li>對某帳號使用「噤聲」功能，可以讓你/妳不看到該帳號的貼文或限時動態，而不被對方發現。你/妳可以：
                      <ol class='font content-hieght'>
                        <li>點選該帳號發佈之貼文或限時動態右上角的「...」；或是至該帳號的個人檔案點選「追蹤中」</li>
                        <li>點選「噤聲」</li>
                      </ol>
                    </li>
                    <li>或是直接取消追蹤該帳號：
                      <ol class='font content-hieght'>
                        <li>點選該帳號發佈之貼文或限時動態右上角的「...」；或是至該帳號的個人檔案點選「追蹤中」</li>
                        <li>點選「取消追蹤」</li>
                      </ol>
                    </li>
                </ul>
                <p class='font content-hieght'>如果只想要看到你/妳想看的資訊（如：商業帳號貼文、其他由演算法推薦的貼文等），你/妳可以試著：</p>
                <ol class='font content-hieght'>
                  <li>點選 IG 首頁左上方「Instagram」</li>
                  <li>點選「追蹤中」查看所有追蹤帳號的貼文；或點選「最愛」查看所有加入最愛清單帳號的貼文</li>
                </ol>"
- title: "設定優先清單"
  guidance_content: "透過設定「最愛」或「摯友」清單，IG 會優先顯示這些帳號的貼文或限時動態。"
  body_content: "<p class='font content-hieght'>設定「最愛」或「摯友」清單的步驟：</p>
                <ol class='font content-hieght'>
                  <li>點選右下角的個人檔案</li>
                  <li>點選右上方「☰」</li>
                  <li>點選「摯友」或「最愛」編輯好友清單</li>
                </ol>"
- title: "關閉 IG 的通知"
  guidance_content: "透過關閉 IG 的通知，讓自己可以更專注在日常的生活，減少來自社群媒體的分心或干擾。"
  body_content: "<p class='font content-hieght'>關閉 IG 通知的步驟：</p>
                <ol class='font content-hieght'>
                  <li>點選右下角的個人檔案</li>
                  <li>點選右上方「☰」</li>
                  <li>點選「設定」</li>
                  <li>點選「通知」</li>
                  <li>根據個人需求選擇 「貼文」、「限時動態和留言」、「訊息」等選項進行設定</li>
                </ol>
                <br>
                <p class='font content-hieght'>除此之外，iPhone 使用者也可以試著利用手機的「工作模式」管理手機的通知喔！</p>"
- title: "有意識地分享動態"
  guidance_content: "在發佈貼文、限時動態之前，試著先思考下面幾件事情，幫助你/妳以「有意識」的方式分享動態："
  body_content: "<ul class='font content-hieght' style='margin: 0px;'>
                    <li>我要發佈的內容是有意義的。</li>
                    <li>我要發佈的內容可不可以帶給別人價值？是不是朋友們想看的？</li>
                    <li>我或是朋友會不會因為這則貼文或限時動態，而有所收穫或感到開心？</li>
                    <li>我要發佈的貼文形式、言語或時機點是不是恰當且可以被理解的？</li>
                    <li>我發佈這則貼文或限時動態只是因為想要分享一些資訊，而不是為了博取大家的同情或關注。</li>
                </ul>
                <br>
                <p class='font content-hieght'>如果你/妳在思考完上面幾件事情後，請在發佈貼文或限時動態前了解以下事情：</p>
                <ul class='font content-hieght' style='margin: 0px;'>
                    <li>可能沒有（或很少）人回覆我的貼文或限時動態。</li>
                    <li>我的貼文或限時動態可能會因為演算法而不被顯示。</li>
                    <li>朋友可能因為在忙別的事情而沒辦法看到我的動態或即時回覆我。</li>
                </ul>"